FROM pcap-registry.pcap-api.svc.cluster.local:5000/utils:openjdk_alpine
# FROM openjdk:alpine

RUN apk add --no-cache python3 py3-pip py3-psutil
RUN pip3 install cbor


COPY exerciseur.jar .
COPY run.py .
COPY enonce_enseignant.yaml .
COPY prologue_code_etu .
COPY épilogue_code_etu .

EXPOSE 8082

HEALTHCHECK --interval=3s CMD [ -e /tmp/.lock ] || exit 1
CMD ["python3", "run.py", "--serveur-http"]
