FROM ghcr.io/openfaas/classic-watchdog:0.1.4 as watchdog
FROM pcap-registry.pcap-api.svc.cluster.local:5000/utils:python_alpine3.8
# FROM python:3.8-alpine

RUN apk add --no-cache \
python3 \
git \
py3-psutil \
R

COPY --from=watchdog /fwatchdog /usr/bin/fwatchdog
RUN chmod +x /usr/bin/fwatchdog
RUN addgroup -S app && adduser app -S -G app
WORKDIR /home/app/

RUN apk add --no-cache gcc python3-dev musl-dev linux-headers make

RUN chown -R app /home/app \
&&  mkdir -p /home/app/python && chown -R app /home/app \
&& mkdir -p /opt/tmp/ \
&& chown -R app  /opt/tmp
USER app
ENV PATH=$PATH:/home/app/.local/bin:/home/app/python/bin/
ENV PYTHONPATH=$PYTHONPATH:/home/app/python
RUN pip3 install \
    git+https://gitlab.com/jrobert/easypython-testeur.git --target=/home/app/python \
    cbor

COPY run.py .
COPY code_ens .

ENV fprocess="python3 run.py"
EXPOSE 8080

HEALTHCHECK --interval=3s CMD [ -e /tmp/.lock ] || exit 1

CMD ["fwatchdog"]
